name: Build

on:
  pull_request:
    branches: [ master, devel ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Load env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo $ENV_FILE > .env

      - name: Create production build
        run: npm run build
